[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required for backend'"]

[start]
cmd = "cd backend && npm start"
